# Generated by Django 2.2.5 on 2019-12-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_id']},
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default='1234'),
            preserve_default=False,
        ),
    ]
