# Generated by Django 2.2.5 on 2020-01-10 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_student_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attempts',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
